<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ukr" xml:lang="ukr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="© Valeriy Sydorenko, 2025">
<meta name="dcterms.date" content="2025-10-03">
<meta name="description" content="Документ зроблено в Quarto">

<title>Лабораторна робота № 2. Розвідувальний аналіз даних</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="lab3_recognize_2025_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/popper.min.js"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab3_recognize_2025_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab3_recognize_2025_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab3_recognize_2025_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab3_recognize_2025_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab3_recognize_2025_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab3_recognize_2025_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="lab3_recognize_2025_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="lab3_recognize_2025_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<link href="lab3_recognize_2025_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

<script src="lab3_recognize_2025_files/libs/datatables-binding-0.34.0/datatables.js"></script>

<script src="lab3_recognize_2025_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="lab3_recognize_2025_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

<link href="lab3_recognize_2025_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

<script src="lab3_recognize_2025_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

<link href="lab3_recognize_2025_files/libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="lab3_recognize_2025_files/libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#що-ви-будете-вміти" id="toc-що-ви-будете-вміти" class="nav-link active" data-scroll-target="#що-ви-будете-вміти">Що ви будете вміти?</a></li>
  <li><a href="#короткі-теоретичні-відомості" id="toc-короткі-теоретичні-відомості" class="nav-link" data-scroll-target="#короткі-теоретичні-відомості">Короткі теоретичні відомості</a>
  <ul class="collapse">
  <li><a href="#що-таке-розвідувальний-аналіз-даних" id="toc-що-таке-розвідувальний-аналіз-даних" class="nav-link" data-scroll-target="#що-таке-розвідувальний-аналіз-даних">Що таке розвідувальний аналіз даних?</a></li>
  <li><a href="#питання" id="toc-питання" class="nav-link" data-scroll-target="#питання">Питання</a></li>
  <li><a href="#типи-шкал-вимірювань" id="toc-типи-шкал-вимірювань" class="nav-link" data-scroll-target="#типи-шкал-вимірювань">Типи шкал вимірювань</a></li>
  <li><a href="#варіація" id="toc-варіація" class="nav-link" data-scroll-target="#варіація">Варіація</a></li>
  <li><a href="#коваріація" id="toc-коваріація" class="nav-link" data-scroll-target="#коваріація">Коваріація</a></li>
  <li><a href="#зниження-розмірності-даних" id="toc-зниження-розмірності-даних" class="nav-link" data-scroll-target="#зниження-розмірності-даних">Зниження розмірності даних</a></li>
  </ul></li>
  <li><a href="#приклад-виконання-індивідуального-завдання" id="toc-приклад-виконання-індивідуального-завдання" class="nav-link" data-scroll-target="#приклад-виконання-індивідуального-завдання">Приклад виконання індивідуального завдання</a>
  <ul class="collapse">
  <li><a href="#постановка-задачі" id="toc-постановка-задачі" class="nav-link" data-scroll-target="#постановка-задачі">Постановка задачі</a></li>
  <li><a href="#виконання-завдання" id="toc-виконання-завдання" class="nav-link" data-scroll-target="#виконання-завдання">Виконання завдання</a></li>
  <li><a href="#індивідуальні-завдання-на-лабораторну-роботу" id="toc-індивідуальні-завдання-на-лабораторну-роботу" class="nav-link" data-scroll-target="#індивідуальні-завдання-на-лабораторну-роботу">Індивідуальні завдання на лабораторну роботу</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><em>Лабораторна робота № 2</em>. Розвідувальний аналіз даних</h1>
</div>

<div>
  <div class="description">
    Документ зроблено в <a href="https://quarto.org/">Quarto</a>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>© <a href="https://www.linkedin.com/in/valeriy-sydorenko-6782279a/">Valeriy Sydorenko</a>, 2025 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Мета:</strong> <em>Засвоєння принципів, знайомство з інструментами та набуття навичок експлораторного (розвідувального) аналізу даних засобами мови програмування R та колекції пакетів <code>dplyr</code>, <code>ggplot2</code>, <code>desctable</code>, <code>GGally</code>, <code>corrplot</code>, <code>PerformanceAnalytics</code>, <code>FactoMineR</code>, <code>factoextra</code>, <code>desctable</code>, <code>ade4</code>, <code>psych</code>, <code>smacof</code>, <code>WVPlots</code>, <code>caret</code>, <code>car</code>.</em></p>
<section id="що-ви-будете-вміти" class="level2">
<h2 class="anchored" data-anchor-id="що-ви-будете-вміти">Що ви будете вміти?</h2>
<ul>
<li>Розв’язувати задачі розвідувального аналізу даних засобами мови R у середовищі IDE RStudio.</li>
<li>Візуалізувати результати аналізу.</li>
<li>Створювати звіт за допомогою видавничої системи Quarto</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Примітка.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Див. <a href="https://vgamaley.github.io/DS-book-lab/lab_3.html">Електронний підручник</a></p>
</div>
</div>
</section>
<section id="короткі-теоретичні-відомості" class="level2">
<h2 class="anchored" data-anchor-id="короткі-теоретичні-відомості">Короткі теоретичні відомості</h2>
<section id="що-таке-розвідувальний-аналіз-даних" class="level3">
<h3 class="anchored" data-anchor-id="що-таке-розвідувальний-аналіз-даних">Що таке розвідувальний аналіз даних?</h3>
<p>У рамках життєвого циклу процесу Data Mining згідно з методологією CRISP DM <span class="citation" data-cites="CRISP_DM">(<a href="#ref-CRISP_DM" role="doc-biblioref">wikipedia 2023a</a>)</span>, першою фазою аналізу даних є “Розуміння даних” (<strong>Understanding</strong>) (рис. 1). До цієї фази входять розглянуті у попередніх лабораторних роботах задачі збору та різного роду трасформації. Наступною важливою задачею даної фази є вивчення даних, що складає основу так званого <a href="https://en.wikipedia.org/wiki/Exploratory_data_analysis"><em>розвідувального аналізу даних</em></a> (Exploratory data analysis, EDA).</p>
<p><strong>Розвідувальний аналіз даних</strong> – аналіз основних властивостей даних, виявлення в них загальних закономірностей, розподілів та аномалій, побудова початкових моделей шляхом їх перетворення та/або представлення у зручному вигляді: графічному, табличному, схем, діаграм і т.ін. <span class="citation" data-cites="EDA">(<a href="#ref-EDA" role="doc-biblioref">wikipedia 2023b</a>)</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/wrangling.png" class="img-fluid figure-img"></p>
<figcaption><em>Рис. 1. Структура задачі розуміння даних у складі Data Science-проекту</em> <span class="citation" data-cites="r4ds">(<a href="#ref-r4ds" role="doc-biblioref">Hadley Wickham 2023</a>)</span></figcaption>
</figure>
</div>
<p>Термін EDA був введений математиком Джоном Тьюкі, який сформулював цілі РАД таким чином:</p>
<ul>
<li>максимальне “проникнення” в дані</li>
<li>виявлення основних структур</li>
<li>вибір найважливіших змінних</li>
<li>виявлення відхилень та аномалій</li>
<li>перевірка основних гіпотез</li>
<li>розробка початкових моделей</li>
</ul>
<p>До основних інструментів РАД відносятся:</p>
<ul>
<li>аналіз ймовірностних розподілів змінних</li>
<li>побудова та аналіз кореляційних матриць</li>
<li>методи зниження розмірності даних: факторний аналіз, дискримінантний аналіз, багатовимірне шкалювання та ін.</li>
</ul>
<p>РАД – це ітеративна процедура, в результаті якої ми:</p>
<ul>
<li>формулюємо запитання щодо наших даних</li>
<li>шукаємо відповідь за допомогою візуалізації, трасформації та моделювання наявних даних</li>
<li>аналізуємо те, що отримано в результаті аналізу та формулюємо нові запитання.</li>
</ul>
<p>“РАД є важливою частиною будь-якого аналізу даних, навіть якщо питання надається вам на блюді, тому що вам завжди потрібно вивчити якість ваших даних. Очищення даних – це лише одне застосування РАД: ви задаєте питання про те, чи відповідають ваші дані вашим очікуванням чи ні.” <span class="citation" data-cites="r4ds">(<a href="#ref-r4ds" role="doc-biblioref">Hadley Wickham 2023</a>)</span>.<br>
Для очищення даних нам потрібно буде розгорнути всі інструменти РАД: візуалізацію, перетворення та моделювання.</p>
</section>
<section id="питання" class="level3">
<h3 class="anchored" data-anchor-id="питання">Питання</h3>
<p>Не існує правил, яким ми могли би керуватися, в частині того, які питання нам слід задавати в процесі своїх досліджень. Проте два типи питань завжди будуть корисними для того, щоб робити відкриття у наших даних. У самій довільній формі ці питання можна сформулювати так <span class="citation" data-cites="r4ds">(<a href="#ref-r4ds" role="doc-biblioref">Hadley Wickham 2023</a>)</span>:</p>
<ul>
<li>Який тип варіації має місце в моїх змінних?</li>
<li>Який тип коваріації має місце між моїми змінними?</li>
</ul>
</section>
<section id="типи-шкал-вимірювань" class="level3">
<h3 class="anchored" data-anchor-id="типи-шкал-вимірювань">Типи шкал вимірювань</h3>
<p>У попередніх темах нами детально були розглянуті шкали вимірювань, математичні операції, які мають сенс з результатми вимірювання у відповідній шкалі та відповідні статистичні характеристики, які мають сенс. Нагадаємо коротко про них:</p>
<ul>
<li><p><strong>Шкала найменувань (номінальна шкала)</strong>, є найпростішою формою шкали, де єдині можливі відносини між елементами – це відносини рівності та нерівності. Ця шкала використовується для класифікації об’єктів на основі спільних характеристик і не передбачає встановлення порядку або відношень “більше-менше” між елементами. Вона застосовується для опису <em>якісних</em> характеристик (експериментальні групи, стать, політичні партії, країни та ідентифікаційні номери, наприклад, номери на майках футболістів).</p></li>
<li><p><strong>Порядкова шкала (рангова шкала)</strong> – це також шкала більш високого рангу, де можливі відношення “більше - менше”, так я к дозволяє ранжувати результати вимірювань у порядку зростання, чи убування певної якості. Наприклад, шкала “Задовільно”, “Добре” і “Відмінно” відповідає ранговій шкалі. “Відмінно” більше “добре”, “ДОбре” більше “Задовільно”, і відповідно “Відмінно” більше “Задовільно”. Однак ми не можемо стверджувати, що різниця між “Відмінно” і “Добре” дорівнює різниці між “Добре” і “Задовільно”. Тому, навіть якщо ми призначимо числові значення, наприклад, “Відмінно” - 5, “Добре” - 3 і “Задовільно” - 2, ми не можемо здійснити арифметичні операції з цією шкалою, такі як обчислення середнього значення.</p></li>
<li><p><strong>Інтервальна шкала (шкала різниць)</strong> – дозволяє порівнювати різниці між інтервалами значень. Наприклад, різниця між 10 градусами Цельсія і 20 градусами Цельсія дорівнює різниці між 80 градусами Цельсія і 90 градусами Цельсія. Для цієї шкали можна виконувати операції порівняння середніх значень, але операції множення та ділення не мають сенсу, оскільки нуль на шкалі різниць є відносним. Наприклад, ми не можемо стверджувати, що 20 градусів Цельсія вдвічі тепліше, ніж 10 градусів Цельсія, оскільки нуль градусів Цельсія – це лише умовна точка, яка відповідає температурі плавлення льоду.</p></li>
<li><p>Шкала відношень, відома також як абсолютна шкала, визначається як “найповноцінніша” шкала, оскільки вона має природний і однозначний початок координат. Наприклад, маса в кілограмах або температура в градусах Кельвіна, а не Цельсія, є прикладами шкал відношень. На цих шкалах можна виконувати всі арифметичні операції, такі як додавання, віднімання, множення та ділення, оскільки нуль на цих шкалах має абсолютне значення. Тобто, на шкалі відношень можна порівнювати відношення значень і робити обчислення, що є неможливим на інших типах шкал.</p></li>
</ul>
<p>найбльш загальні питання розвідувального аналізу даних, зазначені вище щодо типу варіанції і ковариації залишаються актуальними для вимірів у буль-якій шкалі.</p>
</section>
<section id="варіація" class="level3">
<h3 class="anchored" data-anchor-id="варіація">Варіація</h3>
<p><strong>Варіація (Variation)</strong> – це тенденція до змін значення змінної від вимірювання до вимірювання. Ми можете легко помітити варіації в реальному житті; якщо ми двічі вимірюємо постійну змінну, ми отримаємо два різні результати.<br>
Категоричні змінні також можуть відрізнятися, якщо виміри робити для різних суб’єктів (наприклад, кольори очей різних людей) або у різні моменти часу (наприклад, енергетичні рівні електрона в різні моменти). Кожна змінна має свій власний паттерн у варіації, який може виявити цікаву інформацію. Найкращий спосіб зрозуміти цю закономірність – візуалізувати розподіл значень змінної.</p>
<p>Візьмемо для дослідження відомий датасет <code>iris</code> і на його прикладі проведемо розвідувальний аналіз даних, водночас продемонстувавши можливі варіанти відповідного інструментарію.</p>
<section id="візуалізація-розподілу" class="level4">
<h4 class="anchored" data-anchor-id="візуалізація-розподілу">Візуалізація розподілу</h4>
<p>Спочатку завжди доцільно продивитися таблицю датасета, вивести основні статистичні характеристики та побудувати розподіли досліджуваних змінних.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>DT<span class="sc">::</span><span class="fu">datatable</span>(iris)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-64b1874e772c0802c82a" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-64b1874e772c0802c82a">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150"],[5.1,4.9,4.7,4.6,5,5.4,4.6,5,4.4,4.9,5.4,4.8,4.8,4.3,5.8,5.7,5.4,5.1,5.7,5.1,5.4,5.1,4.6,5.1,4.8,5,5,5.2,5.2,4.7,4.8,5.4,5.2,5.5,4.9,5,5.5,4.9,4.4,5.1,5,4.5,4.4,5,5.1,4.8,5.1,4.6,5.3,5,7,6.4,6.9,5.5,6.5,5.7,6.3,4.9,6.6,5.2,5,5.9,6,6.1,5.6,6.7,5.6,5.8,6.2,5.6,5.9,6.1,6.3,6.1,6.4,6.6,6.8,6.7,6,5.7,5.5,5.5,5.8,6,5.4,6,6.7,6.3,5.6,5.5,5.5,6.1,5.8,5,5.6,5.7,5.7,6.2,5.1,5.7,6.3,5.8,7.1,6.3,6.5,7.6,4.9,7.3,6.7,7.2,6.5,6.4,6.8,5.7,5.8,6.4,6.5,7.7,7.7,6,6.9,5.6,7.7,6.3,6.7,7.2,6.2,6.1,6.4,7.2,7.4,7.9,6.4,6.3,6.1,7.7,6.3,6.4,6,6.9,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9],[3.5,3,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,3.7,3.4,3,3,4,4.4,3.9,3.5,3.8,3.8,3.4,3.7,3.6,3.3,3.4,3,3.4,3.5,3.4,3.2,3.1,3.4,4.1,4.2,3.1,3.2,3.5,3.6,3,3.4,3.5,2.3,3.2,3.5,3.8,3,3.8,3.2,3.7,3.3,3.2,3.2,3.1,2.3,2.8,2.8,3.3,2.4,2.9,2.7,2,3,2.2,2.9,2.9,3.1,3,2.7,2.2,2.5,3.2,2.8,2.5,2.8,2.9,3,2.8,3,2.9,2.6,2.4,2.4,2.7,2.7,3,3.4,3.1,2.3,3,2.5,2.6,3,2.6,2.3,2.7,3,2.9,2.9,2.5,2.8,3.3,2.7,3,2.9,3,3,2.5,2.9,2.5,3.6,3.2,2.7,3,2.5,2.8,3.2,3,3.8,2.6,2.2,3.2,2.8,2.8,2.7,3.3,3.2,2.8,3,2.8,3,2.8,3.8,2.8,2.8,2.6,3,3.4,3.1,3,3.1,3.1,3.1,2.7,3.2,3.3,3,2.5,3,3.4,3],[1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,1.5,1.6,1.4,1.1,1.2,1.5,1.3,1.4,1.7,1.5,1.7,1.5,1,1.7,1.9,1.6,1.6,1.5,1.4,1.6,1.6,1.5,1.5,1.4,1.5,1.2,1.3,1.4,1.3,1.5,1.3,1.3,1.3,1.6,1.9,1.4,1.6,1.4,1.5,1.4,4.7,4.5,4.9,4,4.6,4.5,4.7,3.3,4.6,3.9,3.5,4.2,4,4.7,3.6,4.4,4.5,4.1,4.5,3.9,4.8,4,4.9,4.7,4.3,4.4,4.8,5,4.5,3.5,3.8,3.7,3.9,5.1,4.5,4.5,4.7,4.4,4.1,4,4.4,4.6,4,3.3,4.2,4.2,4.2,4.3,3,4.1,6,5.1,5.9,5.6,5.8,6.6,4.5,6.3,5.8,6.1,5.1,5.3,5.5,5,5.1,5.3,5.5,6.7,6.9,5,5.7,4.9,6.7,4.9,5.7,6,4.8,4.9,5.6,5.8,6.1,6.4,5.6,5.1,5.6,6.1,5.6,5.5,4.8,5.4,5.6,5.1,5.1,5.9,5.7,5.2,5,5.2,5.4,5.1],[0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,0.2,0.2,0.1,0.1,0.2,0.4,0.4,0.3,0.3,0.3,0.2,0.4,0.2,0.5,0.2,0.2,0.4,0.2,0.2,0.2,0.2,0.4,0.1,0.2,0.2,0.2,0.2,0.1,0.2,0.2,0.3,0.3,0.2,0.6,0.4,0.3,0.2,0.2,0.2,0.2,1.4,1.5,1.5,1.3,1.5,1.3,1.6,1,1.3,1.4,1,1.5,1,1.4,1.3,1.4,1.5,1,1.5,1.1,1.8,1.3,1.5,1.2,1.3,1.4,1.4,1.7,1.5,1,1.1,1,1.2,1.6,1.5,1.6,1.5,1.3,1.3,1.3,1.2,1.4,1.2,1,1.3,1.2,1.3,1.3,1.1,1.3,2.5,1.9,2.1,1.8,2.2,2.1,1.7,1.8,1.8,2.5,2,1.9,2.1,2,2.4,2.3,1.8,2.2,2.3,1.5,2.3,2,2,1.8,2.1,1.8,1.8,1.8,2.1,1.6,1.9,2,2.2,1.5,1.4,2.3,2.4,1.8,1.8,2.1,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2,2.3,1.8],["setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","setosa","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","versicolor","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica","virginica"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Sepal.Length<\/th>\n      <th>Sepal.Width<\/th>\n      <th>Petal.Length<\/th>\n      <th>Petal.Width<\/th>\n      <th>Species<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Sepal.Length","targets":1},{"name":"Sepal.Width","targets":2},{"name":"Petal.Length","targets":3},{"name":"Petal.Width","targets":4},{"name":"Species","targets":5}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Нижче наведено приклад розподілу категоріальної змінної <code>Species</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Species))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Частоту для кожного значення категоріальної змінної можна обчислита, наприклад, так:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span>  </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Species)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Species  n
1     setosa 50
2 versicolor 50
3  virginica 50</code></pre>
</div>
</div>
<p>Для неперервних змінних доцільно побудувати гістограму.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length), <span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Інтервальна таблиця частот, що відповідає гістограмі, може бути обчислена так:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(<span class="fu">cut_width</span>(Petal.Length, <span class="fl">0.5</span>)) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   cut_width(Petal.Length, 0.5)  n
1                   [0.75,1.25]  4
2                   (1.25,1.75] 44
3                   (1.75,2.25]  2
4                   (2.75,3.25]  1
5                   (3.25,3.75]  6
6                   (3.75,4.25] 16
7                   (4.25,4.75] 22
8                   (4.75,5.25] 23
9                   (5.25,5.75] 16
10                  (5.75,6.25] 10
11                  (6.25,6.75]  5
12                  (6.75,7.25]  1</code></pre>
</div>
</div>
<p>Можна побудувати гістограму для певної долі значень:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>smaller <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Petal.Length <span class="sc">&gt;</span> <span class="fl">2.25</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>smaller <span class="sc">|&gt;</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length)) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Часто буває доцільно поудвати серія гістограм для різних груп спостережень:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">colour =</span> Species)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_freqpoly</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Після того, як ми виконали візуалізацію, що ми маємо знайти на цих графіках? Яка може бути послідовність запитань на наступному етапі?</p>
<p>*Типові запитання з урахуванням специфіка даної задачі можуть виглядати так:</p>
<ul>
<li>Які значення є найбільш поширеними? Чому?</li>
<li>Які значення є рідкісними? Чому? Це відповідає нашим очікуванням?</li>
<li>Чи бачемо ми якісь незвичайні закономірності? Що може їх пояснити?</li>
</ul>
</section>
<section id="незвичайні-значення" class="level4">
<h4 class="anchored" data-anchor-id="незвичайні-значення">Незвичайні значення</h4>
<p>Як правило у вибіркових даних зустірчаються викиди (outliers) – такі значення свідчать або про похибку вимірювання, або про якість надзвичайні причини, що потребують уважного вивчення.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="st">"virginica"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length), <span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Якщо приймається рішення їх видалити, то це можна зроити наступним чином:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>unusual <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Petal.Length <span class="sc">&lt;</span> <span class="dv">3</span> <span class="sc">|</span> Petal.Length <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Species) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Petal.Length)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>unusual</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Sepal.Length Sepal.Width Petal.Length Petal.Width
1           4.6         3.6          1.0         0.2
2           4.3         3.0          1.1         0.1
3           5.8         4.0          1.2         0.2
4           5.0         3.2          1.2         0.2
5           4.7         3.2          1.3         0.2
6           5.4         3.9          1.3         0.4
7           5.5         3.5          1.3         0.2
8           4.4         3.0          1.3         0.2
9           5.0         3.5          1.3         0.3
10          4.5         2.3          1.3         0.3
11          4.4         3.2          1.3         0.2
12          5.1         3.5          1.4         0.2
13          4.9         3.0          1.4         0.2
14          5.0         3.6          1.4         0.2
15          4.6         3.4          1.4         0.3
16          4.4         2.9          1.4         0.2
17          4.8         3.0          1.4         0.1
18          5.1         3.5          1.4         0.3
19          5.2         3.4          1.4         0.2
20          5.5         4.2          1.4         0.2
21          4.9         3.6          1.4         0.1
22          4.8         3.0          1.4         0.3
23          4.6         3.2          1.4         0.2
24          5.0         3.3          1.4         0.2
25          4.6         3.1          1.5         0.2
26          5.0         3.4          1.5         0.2
27          4.9         3.1          1.5         0.1
28          5.4         3.7          1.5         0.2
29          5.7         4.4          1.5         0.4
30          5.1         3.8          1.5         0.3
31          5.1         3.7          1.5         0.4
32          5.2         3.5          1.5         0.2
33          5.4         3.4          1.5         0.4
34          5.2         4.1          1.5         0.1
35          4.9         3.1          1.5         0.2
36          5.1         3.4          1.5         0.2
37          5.3         3.7          1.5         0.2
38          4.8         3.4          1.6         0.2
39          5.0         3.0          1.6         0.2
40          5.0         3.4          1.6         0.4
41          4.7         3.2          1.6         0.2
42          4.8         3.1          1.6         0.2
43          5.0         3.5          1.6         0.6
44          5.1         3.8          1.6         0.2
45          5.4         3.9          1.7         0.4
46          5.7         3.8          1.7         0.3
47          5.4         3.4          1.7         0.2
48          5.1         3.3          1.7         0.5
49          4.8         3.4          1.9         0.2
50          5.1         3.8          1.9         0.4
51          7.2         3.6          6.1         2.5
52          7.4         2.8          6.1         1.9
53          7.7         3.0          6.1         2.3
54          7.3         2.9          6.3         1.8
55          7.9         3.8          6.4         2.0
56          7.6         3.0          6.6         2.1
57          7.7         3.8          6.7         2.2
58          7.7         2.8          6.7         2.0
59          7.7         2.6          6.9         2.3</code></pre>
</div>
</div>
</section>
<section id="пропущені-значення-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="пропущені-значення-missing-values">Пропущені значення (Missing values)</h4>
<p>Часто на практиці дані виявляються некомплектними – мають місце пропущенні дані (<code>NA</code>). У таких випадках відомі два виходи з систуації:</p>
<ul>
<li>видалити некомплектні спостереження</li>
<li>виконати імпутацію пропущених значень – замінити пропущені значення певними у відповідності з якимось алгоритмом.</li>
</ul>
<p>Пакет <code>ggplot2</code> автоматично видаляє некмоплектні дані:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>iris</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
1            5.1         3.5          1.4         0.2     setosa
2            4.9         3.0          1.4         0.2     setosa
3            4.7         3.2          1.3         0.2     setosa
4            4.6         3.1          1.5         0.2     setosa
5            5.0         3.6          1.4         0.2     setosa
6            5.4         3.9          1.7         0.4     setosa
7            4.6         3.4          1.4         0.3     setosa
8            5.0         3.4          1.5         0.2     setosa
9            4.4         2.9          1.4         0.2     setosa
10           4.9         3.1          1.5         0.1     setosa
11           5.4         3.7          1.5         0.2     setosa
12           4.8         3.4          1.6         0.2     setosa
13           4.8         3.0          1.4         0.1     setosa
14           4.3         3.0          1.1         0.1     setosa
15           5.8         4.0          1.2         0.2     setosa
16           5.7         4.4          1.5         0.4     setosa
17           5.4         3.9          1.3         0.4     setosa
18           5.1         3.5          1.4         0.3     setosa
19           5.7         3.8          1.7         0.3     setosa
20           5.1         3.8          1.5         0.3     setosa
21           5.4         3.4          1.7         0.2     setosa
22           5.1         3.7          1.5         0.4     setosa
23           4.6         3.6          1.0         0.2     setosa
24           5.1         3.3          1.7         0.5     setosa
25           4.8         3.4          1.9         0.2     setosa
26           5.0         3.0          1.6         0.2     setosa
27           5.0         3.4          1.6         0.4     setosa
28           5.2         3.5          1.5         0.2     setosa
29           5.2         3.4          1.4         0.2     setosa
30           4.7         3.2          1.6         0.2     setosa
31           4.8         3.1          1.6         0.2     setosa
32           5.4         3.4          1.5         0.4     setosa
33           5.2         4.1          1.5         0.1     setosa
34           5.5         4.2          1.4         0.2     setosa
35           4.9         3.1          1.5         0.2     setosa
36           5.0         3.2          1.2         0.2     setosa
37           5.5         3.5          1.3         0.2     setosa
38           4.9         3.6          1.4         0.1     setosa
39           4.4         3.0          1.3         0.2     setosa
40           5.1         3.4          1.5         0.2     setosa
41           5.0         3.5          1.3         0.3     setosa
42           4.5         2.3          1.3         0.3     setosa
43           4.4         3.2          1.3         0.2     setosa
44           5.0         3.5          1.6         0.6     setosa
45           5.1         3.8          1.9         0.4     setosa
46           4.8         3.0          1.4         0.3     setosa
47           5.1         3.8          1.6         0.2     setosa
48           4.6         3.2          1.4         0.2     setosa
49           5.3         3.7          1.5         0.2     setosa
50           5.0         3.3          1.4         0.2     setosa
51           7.0         3.2          4.7         1.4 versicolor
52           6.4         3.2          4.5         1.5 versicolor
53           6.9         3.1          4.9         1.5 versicolor
54           5.5         2.3          4.0         1.3 versicolor
55           6.5         2.8          4.6         1.5 versicolor
56           5.7         2.8          4.5         1.3 versicolor
57           6.3         3.3          4.7         1.6 versicolor
58           4.9         2.4          3.3         1.0 versicolor
59           6.6         2.9          4.6         1.3 versicolor
60           5.2         2.7          3.9         1.4 versicolor
61           5.0         2.0          3.5         1.0 versicolor
62           5.9         3.0          4.2         1.5 versicolor
63           6.0         2.2          4.0         1.0 versicolor
64           6.1         2.9          4.7         1.4 versicolor
65           5.6         2.9          3.6         1.3 versicolor
66           6.7         3.1          4.4         1.4 versicolor
67           5.6         3.0          4.5         1.5 versicolor
68           5.8         2.7          4.1         1.0 versicolor
69           6.2         2.2          4.5         1.5 versicolor
70           5.6         2.5          3.9         1.1 versicolor
71           5.9         3.2          4.8         1.8 versicolor
72           6.1         2.8          4.0         1.3 versicolor
73           6.3         2.5          4.9         1.5 versicolor
74           6.1         2.8          4.7         1.2 versicolor
75           6.4         2.9          4.3         1.3 versicolor
76           6.6         3.0          4.4         1.4 versicolor
77           6.8         2.8          4.8         1.4 versicolor
78           6.7         3.0          5.0         1.7 versicolor
79           6.0         2.9          4.5         1.5 versicolor
80           5.7         2.6          3.5         1.0 versicolor
81           5.5         2.4          3.8         1.1 versicolor
82           5.5         2.4          3.7         1.0 versicolor
83           5.8         2.7          3.9         1.2 versicolor
84           6.0         2.7          5.1         1.6 versicolor
85           5.4         3.0          4.5         1.5 versicolor
86           6.0         3.4          4.5         1.6 versicolor
87           6.7         3.1          4.7         1.5 versicolor
88           6.3         2.3          4.4         1.3 versicolor
89           5.6         3.0          4.1         1.3 versicolor
90           5.5         2.5          4.0         1.3 versicolor
91           5.5         2.6          4.4         1.2 versicolor
92           6.1         3.0          4.6         1.4 versicolor
93           5.8         2.6          4.0         1.2 versicolor
94           5.0         2.3          3.3         1.0 versicolor
95           5.6         2.7          4.2         1.3 versicolor
96           5.7         3.0          4.2         1.2 versicolor
97           5.7         2.9          4.2         1.3 versicolor
98           6.2         2.9          4.3         1.3 versicolor
99           5.1         2.5          3.0         1.1 versicolor
100          5.7         2.8          4.1         1.3 versicolor
101          6.3         3.3          6.0         2.5  virginica
102          5.8         2.7          5.1         1.9  virginica
103          7.1         3.0          5.9         2.1  virginica
104          6.3         2.9          5.6         1.8  virginica
105          6.5         3.0          5.8         2.2  virginica
106          7.6         3.0          6.6         2.1  virginica
107          4.9         2.5          4.5         1.7  virginica
108          7.3         2.9          6.3         1.8  virginica
109          6.7         2.5          5.8         1.8  virginica
110          7.2         3.6          6.1         2.5  virginica
111          6.5         3.2          5.1         2.0  virginica
112          6.4         2.7          5.3         1.9  virginica
113          6.8         3.0          5.5         2.1  virginica
114          5.7         2.5          5.0         2.0  virginica
115          5.8         2.8          5.1         2.4  virginica
116          6.4         3.2          5.3         2.3  virginica
117          6.5         3.0          5.5         1.8  virginica
118          7.7         3.8          6.7         2.2  virginica
119          7.7         2.6          6.9         2.3  virginica
120          6.0         2.2          5.0         1.5  virginica
121          6.9         3.2          5.7         2.3  virginica
122          5.6         2.8          4.9         2.0  virginica
123          7.7         2.8          6.7         2.0  virginica
124          6.3         2.7          4.9         1.8  virginica
125          6.7         3.3          5.7         2.1  virginica
126          7.2         3.2          6.0         1.8  virginica
127          6.2         2.8          4.8         1.8  virginica
128          6.1         3.0          4.9         1.8  virginica
129          6.4         2.8          5.6         2.1  virginica
130          7.2         3.0          5.8         1.6  virginica
131          7.4         2.8          6.1         1.9  virginica
132          7.9         3.8          6.4         2.0  virginica
133          6.4         2.8          5.6         2.2  virginica
134          6.3         2.8          5.1         1.5  virginica
135          6.1         2.6          5.6         1.4  virginica
136          7.7         3.0          6.1         2.3  virginica
137          6.3         3.4          5.6         2.4  virginica
138          6.4         3.1          5.5         1.8  virginica
139          6.0         3.0          4.8         1.8  virginica
140          6.9         3.1          5.4         2.1  virginica
141          6.7         3.1          5.6         2.4  virginica
142          6.9         3.1          5.1         2.3  virginica
143          5.8         2.7          5.1         1.9  virginica
144          6.8         3.2          5.9         2.3  virginica
145          6.7         3.3          5.7         2.5  virginica
146          6.7         3.0          5.2         2.3  virginica
147          6.3         2.5          5.0         1.9  virginica
148          6.5         3.0          5.2         2.0  virginica
149          6.2         3.4          5.4         2.3  virginica
150          5.9         3.0          5.1         1.8  virginica</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>iris2 <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">ifelse</span>(Petal.Length <span class="sc">&lt;</span> <span class="dv">3</span> <span class="sc">|</span> Petal.Length <span class="sc">&gt;</span> <span class="dv">20</span>, <span class="cn">NA</span>, Petal.Length))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris2, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width)) <span class="sc">+</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="коваріація" class="level3">
<h3 class="anchored" data-anchor-id="коваріація">Коваріація</h3>
<p>Якщо варіація описує поведінку в межах змінної, коваріація описує поведінку між змінними.<br>
<strong>Коваріація (Covariation)</strong> – це схильність значень двох чи більше змінних змінюватися разом. Найкращим способом виявлення коваріації є візуалізація відносин між двома чи більше змінних.</p>
<section id="категоріальні-та-неперервні-змінні" class="level5">
<h5 class="anchored" data-anchor-id="категоріальні-та-неперервні-змінні">Категоріальні та неперервні змінні</h5>
<p>Природнім є рішення щодо вивчення розподілу неперервної змінної, розбивши її на групи у відповідності до значень категоріальної змінної.</p>
<p>Аналіз щільностей розподілів у цьому випадку є не зовсім зручним. Альтернативним варіантом представлення аналогічної інформації є п’ятиквантильний графік (boxplot, box and wiskers plot), відомий як “боксплот”, або “ящик з вусами”. Боксплот акумулює в собі всі найважливіші інтегральні харакетристики стосовно мір центральної тенденції, розсіювання та форми розподілу (рис. 3).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="image/boxplot.png" class="img-fluid figure-img"></p>
<figcaption><em>Рис. 3. Структура боксплота</em> <span class="citation" data-cites="r4ds">(<a href="#ref-r4ds" role="doc-biblioref">Hadley Wickham 2023</a>)</span></figcaption>
</figure>
</div>
<p>Тоді для нашого випадку застосування боксплотів дасть такий результат:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Petal.Length)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="дві-категоріальні-змінні" class="level4">
<h4 class="anchored" data-anchor-id="дві-категоріальні-змінні">Дві категоріальні змінні</h4>
<p>Для візуалізації коваріації між категоріальними змінними необхідно візуалізувати частоти: у вигляді таблиці, або певного графічного візуалізатора. Наприклад:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> diamonds) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_count</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> cut, <span class="at">y =</span> color))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>З результатів видно, що існує певна залежність між кольором діаманта, та якістю його ограненості.</p>
</section>
</section>
<section id="зниження-розмірності-даних" class="level3">
<h3 class="anchored" data-anchor-id="зниження-розмірності-даних">Зниження розмірності даних</h3>
<p><a href="https://en.wikipedia.org/wiki/Dimensionality_reduction"><strong>Зниження розмірності (Dimensionality reduction)</strong></a> – процесс скорочення кількості випадкових змінних шляхом отримання гооловних змінних. Цей процес можно поділити <em>обирання ознак</em> та <em>виділяння ознак</em>.<br>
<em>Обирання ознак</em> – це процес пошуку первісних змінних (факторів), що починаються в рамках фази розуміння даних із залученням експертів предметної галузі і з залученням всього арсеналу інстурментів маніпулювання даними, про що йшлося вище. (Маніпулятивні методики).<br>
<em>Проектування ознак</em> – це перетворення даних з багатовимірного простору у простір простір невеликої кількості вимірів. (Математичні методики). (Далі під зниженням розмірнонсті будем мати на увазі саме проектування ознак). Існує велика кількість лінійних і нелінійних методик зниження розмірності.<br>
Що дає зниження розмірності на практиці? В першу чергу спрощення представлення багатовимірних даних, їх візуалізацію, вирішення задач класифікації та регресії і, власне, краще розуміння процесів, що моделюються.<br>
Одним з фундаментальних лінійних методів зниження розмірності, що широко викорстовується на практиці, є <a href="https://en.wikipedia.org/wiki/Principal_component_analysis">PCA</a> <span class="citation" data-cites="PCA">(<a href="#ref-PCA" role="doc-biblioref">wikipedia 2023c</a>)</span>.</p>
<section id="постановка-задачі-аналізу-методом-главних-компонент-pca" class="level4">
<h4 class="anchored" data-anchor-id="постановка-задачі-аналізу-методом-главних-компонент-pca">Постановка задачі аналізу методом главних компонент (PCA)</h4>
<p>Припустимо <span class="citation" data-cites="PCA">(<a href="#ref-PCA" role="doc-biblioref">wikipedia 2023c</a>)</span>, що ми маємо випадковий вектор <span class="math inline">\(X\)</span>: <span class="math display">\[
X=\begin{pmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{pmatrix}
\]</span></p>
<p>З коваріаційною матрицею:<br>
<span class="math display">\[
var(X) = \Sigma =
\begin{pmatrix}
\sigma_{1}^2 &amp; \sigma_{12} &amp; \ldots &amp; \sigma_{1p}\\
\sigma_{21} &amp; \sigma_{2}^2 &amp; \ldots &amp; \sigma_{2p}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
\sigma_{p1} &amp; \sigma_{p2} &amp; \ldots &amp; \sigma_{p}^2
\end{pmatrix}
\]</span></p>
<p>Мета <a href="https://en.wikipedia.org/wiki/Principal_component_analysis">PCA</a> <span class="citation" data-cites="PCA_b">(<a href="#ref-PCA_b" role="doc-biblioref">Science 2020</a>)</span> полягає в пошуку <span class="math inline">\(k\)</span> лінійних комбінацій <span class="math inline">\(p\)</span> змінних <span class="math inline">\(X\)</span>, що містять найбільшу дисперсію. Лінійна комбінація має насупний вигляд:</p>
<p><span class="math inline">\(Y_1 = a_{11} X_1 + a_{12} X_2 + \cdots + a_{1p} X_p\)</span></p>
<p><span class="math inline">\(Y_2 = a_{21} X_1 + a_{22} X_2 + \cdots + a_{2p} X_p\)</span></p>
<p><span class="math inline">\(\vdots\)</span></p>
<p><span class="math inline">\(Y_k = a_{k1} X_1 + a_{k2} X_2 + \cdots + a_{kp} X_p\)</span></p>
<p>При цьому <span class="math inline">\(\sum\limits_{i=1}^pa_{1i}^2=1\)</span> і т. д.</p>
<p>Дисперсия першої главної компоненти <span class="math inline">\(var(Y_1)=a_1'\Sigma a_1\)</span>, де <span class="math inline">\(\Sigma\)</span> – ковариаційна матриця.</p>
<p>Аналогічно обчислюється дисперсія другої і т. д. головних компонент.</p>
<p>У даній моделі вектори <span class="math inline">\(a_i'=(a_{i1}, a_{i2},...,a_{ip})',\;i=\overline{1,p}\)</span> представляють <em>власні вектори</em> ковариаційної матриці <span class="math inline">\(\Sigma\)</span>, тоді як дисперсія <span class="math inline">\(i\)</span>-ої головної компоненти дорівнює <em>власному значенню</em> матриці ковариацій:</p>
<p><span class="math inline">\(var(Y_i)=\lambda_i\)</span>.</p>
<p><em>Загальна дисперсія</em> вибірки дорівнює <span class="math inline">\(\sum\limits_{i=1}^p\lambda_{i}.\)</span><br>
Метод головних компонент (PCA) вирішуючи задачу зниження розмірності дозволяє одночасно вирішити задачу сегементації (кластеризації) – тобто з’ясувати, чи є досліджувані дані однорідними, чи сегментовані на групи зі схожими ознаками. Відповідь на це питання є однією з головних задач експлораторного аналізу, що передує етапу побуви більш складних моделей класифікації, регресії чи моделей на основі асоціативних правил.</p>
<p>В арсеналі R існує багато інструментів для реалізації зниження розмірності, зокрема PCA.</p>
</section>
</section>
</section>
<section id="приклад-виконання-індивідуального-завдання" class="level2">
<h2 class="anchored" data-anchor-id="приклад-виконання-індивідуального-завдання">Приклад виконання індивідуального завдання</h2>
<section id="постановка-задачі" class="level3">
<h3 class="anchored" data-anchor-id="постановка-задачі">Постановка задачі</h3>
<p>Дано стандартний багатовимірний набір даних <a href="https://en.wikipedia.org/wiki/Iris_flower_data_set">Іриси Фішера (англ. Iris flower data set)</a>.<br>
Іриси Фішера складаються з даних про 150 вимірювань ірисів з трьох видів —- Iris setosa, Iris virginica і Iris versicolor, по 50 вимірювань на вид. Для кожного екземпляра вимірювалися чотири характеристики (в сантиметрах):</p>
<ul>
<li>Довжина зовнішньої частки оцвітини (англ. sepal length);</li>
<li>Ширина зовнішньої частки оцвітини (англ. sepal width);</li>
<li>Довжина внутрішньої частки оцвітини (англ. petal length);</li>
<li>Ширина внутрішньої частки оцвітини (англ. petal width).</li>
</ul>
<p>Для даного набору виконати розвідувальний аналіз даних.<br>
Необхідно дати відповідь на такі питання:</p>
<ul>
<li>чи є дані комплектними? з’ясувати характер розподілу змінних.</li>
<li>чи пов’язані між собою характеристики? якщо пов’язані, то які і як?</li>
<li>чи існує проста структура, яка дозволяє описати дані об’єкти в просторі розмірністю менш ніж <code>4</code>? якщо існує – побудувати таку модель.</li>
<li>чи є всі три види ірисів однорідними у даному просторі ознак? якщо ні, то виконати сегментацію – знайти групи з однорідними ознаками.<br>
Результати представити із застосуванням простих і зрозумілих візуалізаторів.</li>
</ul>
<!-- Іриси Фішера (англ. Iris flower data set) — це багатовимірний набір даних для задачі класифікації, на прикладі якого англійський статистик та біолог Рональд Фішер в 1936 році продемонстрував роботу розробленого ним методу дискримінантного аналізу. Іноді його також називають ірисами Андерсона — через те, що дані були зібрані американським ботаніком Едгаром Андерсоном. Цей набір даних став класичним і часто використовується в літературі для ілюстрації роботи різних статистичних алгоритмів. -->
</section>
<section id="виконання-завдання" class="level3">
<h3 class="anchored" data-anchor-id="виконання-завдання">Виконання завдання</h3>
<p>Дані з досліджуваного набору мають наступний вигляд:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># iris |&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   desctable()</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Обчислимо і дослідимо сумарні статистики.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Сводные выборочные характеристики</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                </code></pre>
</div>
</div>
<p>Що ми бачимо?</p>
<ul>
<li>всі дані мають числову природу</li>
<li>дані комплектні: відстуні пропущені значення</li>
<li>відсутні нульові значення – це знімає можливі проблеми при трансформації</li>
<li>відсутні надвелики значення – надвелики значення кожен раз потребують серйозної уваги і аналізу можливих причин, що їх викликали</li>
<li>по всіх змінних дані мають варіацію по унікальним значенням одного порядку.</li>
</ul>
<p>Дослідимо закони розподілу кожної з чотирьох змінних. Для цього побудуємо серію гістограм для кожної з чотирьох числових змінних: <code>"Sepal.Length"</code>, <code>"Sepal.Width"</code>, <code>"Petal.Length"</code>, <code>"Petal.Width"</code></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Побудова 4x4 матриці гістограм і щільності нормального розподілу з відносними частками</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>Species) <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.2</span>, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"lightblue"</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"dark grey"</span>, </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density))) <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Значення"</span>, <span class="at">y =</span> <span class="st">"Відносна частота"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Що ми бачимо?</p>
<ul>
<li>статистичні розподіли змінних <code>"Sepal.Length"</code>, <code>"Sepal.Width"</code> мають дзвоноподібну форму, наближену до нормального. Враховуючи, що значення оцінок асимметрії та ексцесу несуттєво відрізняються від нуля, в першому наближенні можна вважати дані розподіли нормальними. Про що це говорить і що це дає? По-перше, це говорить про те, що доля малих і великих даних врівноважують одна одну, по-друге, нормальність законів розподілу досліджуваних величин, або, принаймні, “натяк” на нормальність <strong>завжди добре</strong>, тому що класичними передумовами для коректної побудови великої кількості різного роду моделей вимагає від даних нормального закону розподілу, чи, принаймні, симетричності закону розподілу. В нашому випадку це є передумовою однорідного розподілу спостережень у просторі інформативних ознак, що є позитивним моментом при вирішенні задачі сегментації.<br>
</li>
<li>статистичні розподіли змінних <code>"Petal.Length"</code>, <code>"Petal.Width"</code> на відміну від двох інших, мають чітку бімодальну структуру, що гооврить про явно виражену неоднорідність даних і про те, що саме ці дві змінні є дискримінуючими у просторі досліджуваних ознак; це важливо для побудови задачі сегментації</li>
</ul>
<p>Для відповіді на питання, чи пов’язані між собою змінні, застосуємо кореляційний аналіз. З урахуванням числової природи даних, для оцінки кореляції скористаємося коефіцієнтом кореляції Пірсона. Враховуючі багатомірний аналіз початкових даних, важливо вдало підібрати візуалізатор. Нижче запропоновано два з найбільш відомих і поширених.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Кореляція Пірсона</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Species) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">cor</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">corrplot</span>(<span class="at">order =</span> <span class="st">"hclust"</span>, <span class="at">tl.col=</span><span class="st">'black'</span>, <span class="at">tl.cex=</span>.<span class="dv">75</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>  <span class="co"># chart.Correlation(histogram=TRUE, pch=19)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pairs(iris[1:4], main="Edgar Anderson's Iris Data", font.main=4, pch=19)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Species) <span class="sc">|&gt;</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>( <span class="at">main=</span><span class="st">"Edgar Anderson's Iris Data"</span>, <span class="at">font.main =</span> <span class="dv">4</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> iris<span class="sc">$</span>Species)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pairs(iris[1:4], main="Edgar Anderson's Iris Data", font.main = 4, pch = 19, col = iris$Species)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_iris <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Species)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># df_iris |&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a> <span class="co">#   correlation_table("")</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>df_iris <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>() <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># head(11)</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Таблица оценок коэффициентов корреляции"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Таблица оценок коэффициентов корреляции</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Sepal.Length</th>
<th style="text-align: right;">Sepal.Width</th>
<th style="text-align: right;">Petal.Length</th>
<th style="text-align: right;">Petal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.1175698</td>
<td style="text-align: right;">0.8717538</td>
<td style="text-align: right;">0.8179411</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: right;">-0.1175698</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.4284401</td>
<td style="text-align: right;">-0.3661259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: right;">0.8717538</td>
<td style="text-align: right;">-0.4284401</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.9628654</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width</td>
<td style="text-align: right;">0.8179411</td>
<td style="text-align: right;">-0.3661259</td>
<td style="text-align: right;">0.9628654</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Що ми бачимо?</p>
<ul>
<li>має місце сильний позитивний кореляційний зв’язок між змінною <code>Sepal.Length</code> та змінними <code>Petal.Length</code>, <code>Petal.Width</code>; на кореляційних полях чітко видно наявність даної кореляції</li>
<li>на кореляційних полях чітко видно наявність неоднородності даних – дані чітко поділяються на гомогенні групи за змінною <code>Species</code></li>
<li>має місце слабкий від’ємний кореляційний зв’язок <code>Petal.Length</code> і <code>Sepal.Width</code>; дана кореляція є уявною в силу сегментованості даних по змінній <code>Species</code>: якщо уважно дослідити форму кореляційних полів для кожного значення данної змінної, то можна побачити, що всередині кожного сегменту має місце позитивна кореляція</li>
</ul>
<p>Що це нам дає?</p>
<ul>
<li>наявність високого ступеня кореляції дає можливість знизити розмірність даних і знайти просту структуру у просторі меншої розмірності</li>
<li>у просторі меншої розмірності можна можна виконати сегментацію даних.</li>
</ul>
<p>Для зниження розмірності і одночасно сегментації даних скористаємося методом головних компонент (PCA).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PCA </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>resPCA <span class="ot">&lt;-</span> iris <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Species) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">PCA</span>(<span class="at">ncp =</span> <span class="dv">8</span>, <span class="at">graph =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># власні значення та кумулятивний процент</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>eigenvalues <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(resPCA<span class="sc">$</span>eig)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>cumVar <span class="ot">&lt;-</span> <span class="fu">round</span>(eigenvalues<span class="sc">$</span><span class="st">`</span><span class="at">cumulative percentage of variance</span><span class="st">`</span>[<span class="fu">length</span>(eigenvalues<span class="sc">$</span>eigenvalue[eigenvalues<span class="sc">$</span>eigenvalue <span class="sc">&gt;=</span> <span class="fl">0.9</span>])], <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  eigenvalues, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Власні значення (eigenvalues) і сумарний процент поясненої дисперсії"</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Власні значення (eigenvalues) і сумарний процент поясненої дисперсії</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 30%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">eigenvalue</th>
<th style="text-align: right;">percentage of variance</th>
<th style="text-align: right;">cumulative percentage of variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">comp 1</td>
<td style="text-align: right;">2.9184978</td>
<td style="text-align: right;">72.9624454</td>
<td style="text-align: right;">72.96245</td>
</tr>
<tr class="even">
<td style="text-align: left;">comp 2</td>
<td style="text-align: right;">0.9140305</td>
<td style="text-align: right;">22.8507618</td>
<td style="text-align: right;">95.81321</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comp 3</td>
<td style="text-align: right;">0.1467569</td>
<td style="text-align: right;">3.6689219</td>
<td style="text-align: right;">99.48213</td>
</tr>
<tr class="even">
<td style="text-align: left;">comp 4</td>
<td style="text-align: right;">0.0207148</td>
<td style="text-align: right;">0.5178709</td>
<td style="text-align: right;">100.00000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_screeplot</span>(resPCA, <span class="at">addlabels =</span> <span class="cn">TRUE</span>,  <span class="at">ncp=</span><span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Чщо ми бачимо?<br>
Ми маємо <span class="math inline">\(p=\)</span> 2 головних компонент, які пояснюють 95.81 % дисперсії. Це значить, що м маємо всього дві нові компоненти замість чотирьох і практично без втрати інформації можемо представити всі спостереження в системі двох координат на площині: перша компонента по осі <code>Х</code>, друга – по осі Y (див. рис.).<br>
Проаналізуємо детально структуру двох перших компонент, виключивши решту незначимих (див. табл. і рис.).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Навантаження для двох перших головних компонент</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  resPCA<span class="sc">$</span>var<span class="sc">$</span>coord[ ,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Таблиця навантажень"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Таблиця навантажень</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Dim.1</th>
<th style="text-align: right;">Dim.2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: right;">0.8901688</td>
<td style="text-align: right;">0.3608299</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: right;">-0.4601427</td>
<td style="text-align: right;">0.8827163</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: right;">0.9915552</td>
<td style="text-align: right;">0.0234152</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width</td>
<td style="text-align: right;">0.9649790</td>
<td style="text-align: right;">0.0639998</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Що ми бачимо?</p>
<ul>
<li>Структуру першої компоненти головним чином складають три початкові змінні: <code>Sepal.Length</code>, <code>Petal.Length</code>, <code>Petal.Width</code>; як і прогнозувалося раніше, саме за цією компонентою відбувається дискримінація (розрізнення) трьох різних сегментів трьох типів ірисів</li>
<li>основне навантаження на другу компоненту складає змінна <code>Sepal.Width</code> – всі три види ірисів можуть мати досить велику варіацію за цим параметром.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Biplot of individuals and variables</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(resPCA,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">geom =</span> <span class="fu">c</span>(<span class="st">"point"</span>),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                <span class="co"># label = "none", # hide individual labels</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">habillage =</span> <span class="fu">as.factor</span>(iris<span class="sc">$</span>Species), <span class="co"># color by groups</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">axes =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"ind"</span>, <span class="st">"ind.sup"</span>, <span class="st">"quali"</span>, <span class="st">"var"</span>, <span class="st">"quanti.sup"</span>),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">select.var =</span> <span class="fu">list</span>(<span class="at">name =</span> <span class="fu">c</span>(<span class="st">"Sepal.Length"</span>, <span class="st">"Sepal.Width"</span>, <span class="st">"Petal.Length"</span>, <span class="st">"Petal.Width"</span>)),</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>             <span class="co"># select.var = list(contrib = 8),</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>             <span class="co"># label = c("ind.sup"),</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>, <span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>),</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>             <span class="co"># alpha.var = c("contrib"),</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>             <span class="co"># col.ind = c("contrib"),</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>             <span class="co"># col.ind.sup = c("contrib"),</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">addEllipses =</span> <span class="cn">TRUE</span> <span class="co"># Concentration ellipses</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>             ) <span class="sc">+</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab3_recognize_2025_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Таким чином, з’ясовано, шо початкові дані не є однорідними. Три типи ірисів різняться за довжинами внутрішніх часток оцвітини (petal length) та шириною внутрішньої частки оцвітини (petal width). Завдяки наявності кореляцій у початкових змінних, спостереження вдалося добре описати у просторі двох інтегральних показників. Знайдені кластери характерні для трьох типів ірисів і у майбутньому можуть бути використані для написання класифікатора з метою розпізнавання нових об’єктів.</p>
</section>
<section id="індивідуальні-завдання-на-лабораторну-роботу" class="level3">
<h3 class="anchored" data-anchor-id="індивідуальні-завдання-на-лабораторну-роботу">Індивідуальні завдання на лабораторну роботу</h3>
<p>Видає викладач.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-r4ds" class="csl-entry" role="listitem">
Hadley Wickham, Garrett Grolemund. 2023. <em>R for Data Science</em>. <a href="http://r4ds.had.co.nz/index.html">http://r4ds.had.co.nz/index.html</a>.
</div>
<div id="ref-PCA_b" class="csl-entry" role="listitem">
Science, Eberly College of. 2020. <span>“STAT 505: Applied Multivariate Statistical Analysis.”</span> Course materials. <a href="http://belousovv.ru/markdown_syntax#fnref:2">http://belousovv.ru/markdown_syntax#fnref:2</a>.
</div>
<div id="ref-CRISP_DM" class="csl-entry" role="listitem">
wikipedia. 2023a. <span>“Cross-Industry Standard Process for Data Mining.”</span> Article. <a href="https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining">https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining</a>.
</div>
<div id="ref-EDA" class="csl-entry" role="listitem">
———. 2023b. <span>“Exploratory Data Analysis.”</span> Article. <a href="https://en.wikipedia.org/wiki/Exploratory_data_analysis">https://en.wikipedia.org/wiki/Exploratory_data_analysis</a>.
</div>
<div id="ref-PCA" class="csl-entry" role="listitem">
———. 2023c. <span>“Principal Component Analysis.”</span> Article. <a href="https://en.wikipedia.org/wiki/Principal_component_analysis">https://en.wikipedia.org/wiki/Principal_component_analysis</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>